data_root: 'D:\cv_contest\food-attractive-DL\dataset'
val_size: 0.15
backbone: "convnext" # Changed from resnet50
pretrained: True
freeze_backbone: False
hidden_size: 512
dropout_prob: 0.3
batch_size: 32
epochs: 3
lr: 0.0001
weight_decay: 0.0001
save_dir: "checkpoints"
